### ISSUE TITLE
No longer working? Help wanted.

### ISSUE THREAD

**Issue by ooloops** [GMMan/PxcViewDumpingShim#2]
I downloaded the DLL, renamed and replaced the existing DLL in C:\Program Files (x86)\VitalSource Bookshelf but there does not appear to be any prompt to save the PDF. Am I doing something wrong or is this tool defunct?

**Comment by GMMan** [comment]
The DLL only works if the the program calls it to load a PDF file. Make sure the book you're trying to read is in PDF format, and not e.g. EPUB or loose images.

**Comment by ooloops** [comment]
Ah, damn, didn't check that before writing this sorry. Any tips for downloading an epubbook formatted textbook?

**Comment by GMMan** [comment]
You might be able to pull pages out of temporary internet files on newer versions of Windows, but I have not tested that.

**Comment by GMMan** [comment]
Have a look at [Extractor.epub](http://www.mobileread.com/forums/showthread.php?t=258568), which will be able to extract epubbooks.
