### ISSUE TITLE
Crashes when Opening

### ISSUE THREAD

**Issue by fletchto99** [GMMan/PxcViewDumpingShim#3]
Hey there.

I'm running windows 10 with bookshelf v 6.7.0(16).

When I open bookshelf after following the readme, it crashes instantly. Did the new updates by chance break this method?

**Comment by GMMan** [comment]
You probably didn't install the redistributable or rename the original DLL. In any case, it's a moot point as this version of Bookshelf validates the digital signature of the DLL, and quits if it can't be validated.

**Comment by fletchto99** [comment]
@GMMan I made sure to install the redistributable. I also renamed the original dll with an "_" before the name. I assume this dll calls out to that one once the saving process is complete? Anyhow as soon as I open bookshelf it still crashes.

Perhaps there's a way to downgrade bookshelf to prevent the dll from validating and quitting the application?

**Comment by GMMan** [comment]
You probably didn't rename the original file correctly. It's supposed to be named "_pxcvw.dll". You can probably find the previous version of Bookshelf on Internet Archive.

**Comment by j3ngel** [comment]
Which redistributable are you referring to?
