### ISSUE TITLE
VitalSource Freezes Up

### ISSUE THREAD

**Issue by cpagravel** [GMMan/PxcViewDumpingShim#5]
I've compiled the solution using Visual Studio 2015 with no errors. The old pcxview.dll was renamed to '_pcxvw.dll' and I put 'pcxview.dll' that I compiled, into the VitalSource directory. I don't know what was meant by changing the original dll's import name. 

Anyway, I ran Vitalsource and opened a pdf book and it freezes on me.

Also, I'm using VitalSource v6.2

**Comment by cpagravel** [comment]
The problem was solved once i used the original pcxview.dll that was supplied here.

**Comment by cpagravel** [comment]
If this is the case, I would like to know why the one I compiled didn't work? I was using Visual Studio 2015, but it compiled without errors.

**Comment by GMMan** [comment]
Simply, you didn't change the name of the original DLL to import within the compiled DLL. Take a look at the difference with CFF Explorer or another PE editor.
