### ISSUE TITLE
Which version of bookshelf works with this dll?

### ISSUE THREAD

**Issue by googlebot-xx** [GMMan/PxcViewDumpingShim#7]
I test v6.2.3,  dll not working,  bookshelf fail to open..

**Comment by GMMan** [comment]
Did you install the redist linked in the release and followed the readme?

**Comment by googlebot-xx** [comment]
I did install x64 version vc redist, maybe should install 32bit version.
I will try today and tell you result.

**Comment by googlebot-xx** [comment]
install vcredist_x86-2013, it works.

On Mon, Mar 28, 2016 at 1:23 AM, Yukai Li notifications@github.com wrote:

> Did you install the redist linked in the release and followed the readme?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/GMMan/PxcViewDumpingShim/issues/7#issuecomment-202239440

## 

Kevin Pan
