### ISSUE TITLE
VitalSource doesn't use pxcview.dll

### ISSUE THREAD

**Issue by ryandward** [GMMan/PxcViewDumpingShim#8]
GMMan, thank you for all your hard work on this project. I am currently trying to use the compiled DLL, using everything you said. However, nothing happens. Even when I completely delete the pxcview.dll, VitalSource is able to load pdfbooks. 

Am I doing something wrong?

**Comment by GMMan** [comment]
Correct, current version of Bookshelf has the PDF renderer compiled in its base assembly. The pxcview.dll is only there for show (and rather poorly, since they didn't even bother to sign it last I checked).

**Comment by ryandward** [comment]
Ok that explains it! Thank you
